version: '3'
services:
  node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    container_name: esw-node1
    environment:
      - node.name=node1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=node2"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      esnet:

  node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    container_name: esw-node2
    environment:
      - node.name=node2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=node1"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      esnet:

  kibana:
    container_name: esw-kibana
    image: docker.elastic.co/kibana/kibana:6.8.9
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      esnet:
    depends_on:
      - node1


volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: